title: Ionic Builds
description: >- # this means to ignore newlines until "baseurl:"
  Ionic Builds
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: /our-work/:title
image_dir: /assets/images/
svg_dir: /assets/svg/
uploads_dir: /assets/images/uploads/

collections:
  work:
    output: true

defaults:
  - scope:
      path: ''
      type: 'work'
    values:
      layout: 'work/work'

include: ['_pages']
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
